### ISSUE TITLE
jsonschema conflict with jupyterlab_server

### ISSUE THREAD

**Issue by tharwan** [ssciwr/ipywidgets-jsonschema#82]
the current version of [jupyterlab_server](https://github.com/jupyterlab/jupyterlab_server/blob/b26c866a662af2c93a5538a8b279c4426d7bc85d/pyproject.toml#L35) depends on jsonschema > 4.18 which makes it incompatible with the requirements here.

Is it possible to simply relax the requirements? Could I contribute with a PR?

**Comment by dokempf** [comment]
Thanks for noticing. I remember that there the jsonschema package was very much "in flux" when I was developing this, so I pinned the old, stable version. That being said, I am very open to PRs porting it to the latest version.

**Comment by dokempf** [comment]
Thanks @tharwan for your work. It is merged and released as v1.0.1 on PyPI, conda-forge is on its way!
