### ISSUE TITLE
Option to show descriptions above/below inputs

### ISSUE THREAD

**Issue by tharwan** [ssciwr/ipywidgets-jsonschema#86]
Hi, 

I noticed that currently the descriptions are only rendered in the tooltips. I think it would be nice to have the option to show them in the UI permanently so they are easier to discover. 

Would you be interested in another PR for such a feature?

**Comment by dokempf** [comment]
Yes, I am absolutely open to this. I think it would be good to enable/disable this via a `show_description` parameter to the `Form.__init__`.

**Comment by dokempf** [comment]
Implemented in #88
